export const GET_ALL_USER_COMMENT_SAGA = "GET_ALL_USER_COMMENT_SAGA";

export const GET_ALL_USER_COMMENT = "GET_ALL_USER_COMMENT";
export const CREATE_USER_COMMENT = "CREATE_USER_COMMENT";
export const EDIT_USER_COMMENT = "EDIT_USER_COMMENT";
export const DELETE_USER_COMMENT = "DELETE_USER_COMMENT";
